language: ruby

env:
  - RAILS_VERSION=3
  - RAILS_VERSION=4
  - RAILS_VERSION=5
  - RAILS_VERSION=6
  - RAILS_VERSION=master

rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

matrix:
  exclude:
    - rvm: 1.9
      env: RAILS_VERSION=5
    - rvm: 1.9
      env: RAILS_VERSION=6
    - rvm: 1.9
      env: RAILS_VERSION=master
    - rvm: 2.0
      env: RAILS_VERSION=5
    - rvm: 2.0
      env: RAILS_VERSION=6
    - rvm: 2.0
      env: RAILS_VERSION=master
    - rvm: 2.1
      env: RAILS_VERSION=5
    - rvm: 2.1
      env: RAILS_VERSION=6
    - rvm: 2.1
      env: RAILS_VERSION=master
    - rvm: 2.2
      env: RAILS_VERSION=6
    - rvm: 2.2
      env: RAILS_VERSION=master
    - rvm: 2.3
      env: RAILS_VERSION=6
    - rvm: 2.3
      env: RAILS_VERSION=master
    - rvm: 2.4
      env: RAILS_VERSION=6
    - rvm: 2.4
      env: RAILS_VERSION=master
