# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# frozen_string_literal: true

Gem::Specification.new do |s|
  s.name = 'gravatar_image_tag'
  s.version = '1.2.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.authors = ['Michael Deering']
  s.date = '2013-11-11'
  s.email = 'mdeering@mdeering.com'
  s.extra_rdoc_files = [
    'README.textile'
  ]
  s.files = [
    'MIT-LICENSE',
    'README.textile',
    'Rakefile',
    'lib/gravatar_image_tag.rb',
    'spec/gravatar_image_tag_spec.rb',
    'spec/test_helper.rb'
  ]
  s.homepage = 'http://github.com/mdeering/gravatar_image_tag'
  s.require_paths = ['lib']
  s.rubygems_version = '1.8.24'
  s.summary = 'A configurable and documented Rails view helper for adding gravatars into your Rails application.'

  if s.respond_to? :specification_version
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_development_dependency('actionpack', ['~> 3.2.0'])
      s.add_development_dependency('activesupport', ['~> 3.2.0'])
      s.add_development_dependency('guard', ['>= 0'])
      s.add_development_dependency('guard-rspec', ['>= 0'])
      s.add_development_dependency('jeweler', ['>= 0'])
      s.add_development_dependency('rb-fsevent', ['~> 0.9'])
      s.add_development_dependency('rspec', ['>= 0'])
    else
      s.add_dependency('actionpack', ['~> 3.2.0'])
      s.add_dependency('activesupport', ['~> 3.2.0'])
      s.add_dependency('guard', ['>= 0'])
      s.add_dependency('guard-rspec', ['>= 0'])
      s.add_dependency('rb-fsevent', ['~> 0.9'])
      s.add_dependency('rb-fsevent', ['~> 0.9'])
      s.add_dependency('rspec', ['>= 0'])
    end
  else
    s.add_dependency('activesupport', ['~> 3.2.0'])
    s.add_dependency('activesupport', ['~> 3.2.0'])
    s.add_dependency('jeweler', ['>= 0'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('rspec', ['>= 0'])
    s.add_dependency('rspec', ['>= 0'])
  end
end
